mode: "8-servo"
spool_diameter_cm: 2.0
ticks_per_revolution: 4096
servo_ids: [1, 2, 3, 4, 5, 6, 7, 8]
tendon_to_servo: [1, 2, 3, 4, 5, 6, 7, 8]
tightening_rotation_by_servo:
  1: "cw"
  2: "cw"
  3: "cw"
  4: "cw"
  5: "cw"
  6: "cw"
  7: "cw"
  8: "cw"
